model:
  feature_extractor:
    input_dim: 1000  # Number of gene expression features (set to 1000 with current data)
    hidden_dims: [512, 256, 128]  # Adjusted for smaller input dimension
    dropout: 0.2
  
  drug_predictor:
    input_dim: 128  # Matches last hidden dim of feature extractor
    hidden_dims: [64, 32]
    output_dim: 1
    dropout: 0.2

  domain_discriminator:
    input_dim: 128  # Matches last hidden dim of feature extractor
    hidden_dims: [128, 64]
    output_dim: 2  # 2 domains: cell_line vs patient
    dropout: 0.2

training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 100
  lambda_domain: 1.0  # Weight for domain adversarial loss
  
  # Learning rate scheduling
  scheduler:
    type: "step"
    step_size: 30
    gamma: 0.1

data:
  # Data paths - processed data from download and processing scripts
  # Run: python scripts/download_drug_response_data.py
  #      python scripts/process_drug_response_data.py
  gdsc_path: "data/processed/gdsc_log_normalised.csv"
  tcga_path: "data/processed/tcga_log_normalised.csv"
  # Data preprocessing
  normalize: true
  log_transform: true
  
  # Cross-validation
  cv_folds: 5
  test_split: 0.2

evaluation:
  metrics: ["mse", "mae", "pearson", "spearman"]
  save_predictions: true

logging:
  log_dir: "experiments"
  tensorboard: true
  checkpoint_freq: 10